# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main

pool:
  vmImage: windows-latest

parameters:
  - name: stages
    type: object
    default:
      - name : dev
      - name : tst
      - name : stg
      - name : prod

stages:
  - ${{each stage in parameters.stages}}:
    - stage: ${{stage.name}}
      variables:
      - group: vg-${{stage.name}}
      jobs:
        - deployment: ${{stage.name}}_deploy
          environment: ${{stage.name}}_environment
          workspace:
            clean: all
          strategy:
            runOnce:
              deploy:
                steps:
                - script: echo Hello, world!
                  displayName: 'Hello World Test'

                - script: |
                    echo Display Environment - $(environment).
                  displayName: 'Environment Test'













